### ISSUE TITLE
Error getting slots when a node is down

### ISSUE THREAD

**Issue by i2dcarrasco** [steve0511/resty-redis-cluster#58] opened 2020-04-21 12:02 UTC
Hello,

I'm testing failover situations on my redis cluster and I've noticed that lua script stopped working after stop a node.

My setup is a redis cluster with 6 nodes (3 master, +1 replica on every master), and I've configured the lua redis cluster as suggested on the readme.
```
red_config = {
    name = "Cluster",
    serv_list = {
        {ip = srv1, port = 6379},
        {ip = srv2, port = 6379},
        {ip = srv3, port = 6379},
        {ip = srv4, port = 6379},
        {ip = srv5, port = 6379},
        {ip = srv6, port = 6379},
    },
    keepalive_timeout = 60000,
    keepalive_cons = 1000,
    connection_timout = 1000,
    max_redirection = 5,
    auth = nil,
}
```

Was working fine, but after stop the first master, my lua script has stopped working giving errors getting the slots from Redis Cluster:

```
2020/04/21 11:38:40 [error] 17#17: *2275 [lua] rediscluster.lua:179: init_slots(): failed to acquire the lock in initialization slot cache: timeout, client: 46.25.49.202, server: www.example.com, request: "GET /index.php?action=abrir_capa_login&idioma=spa HTTP/1.1", host: "www.example.com", referrer: "https://www.example.com/"
2020/04/21 11:38:40 [error] 17#17: *2275 lua entry thread aborted: runtime error: .../tmp.ctbxBlkqPA/resty-redis-cluster/lib/rediscluster.lua:310: attempt to index local 'slots' (a nil value)
stack traceback:
coroutine 0:
	.../tmp.ctbxBlkqPA/resty-redis-cluster/lib/rediscluster.lua: in function 'handleCommandWithRetry'
	.../tmp.ctbxBlkqPA/resty-redis-cluster/lib/rediscluster.lua:430: in function 'exists'
```

I'm sure that the cluster still working, because I've look into the server log and I've seen how it failover to slave:
```
716:M 21 Apr 2020 13:17:33.577 * Marking node a012fdaf648326f2b47fd220b932962ef3e3cb37 as failing (quorum reached).
716:M 21 Apr 2020 13:17:34.228 # Failover auth granted to e2af791d8f96c549b03c399cc0beb34ca0cbe7c0 for epoch 7
```
(ignore timestamps, one is +2 and the other UTC)
and also the PHP sessions are stored on same cluster, and the webpage still working without problems.

I suspect that is always trying to connect to first node and is not doing the failover, because I've removed the first node IP (wich I've stopped) and it started working again.

Is there any way to failover to another server if the first fails?, maybe I've not configured the module correctly.

Best regards and thanks.

**Comment by toredash** [comment] 2020-04-21 19:10
@i2dcarrasco Are you sure you are using the latest version of the code ?  I got code merged in (https://github.com/steve0511/resty-redis-cluster/pull/55) that allows the cluster size to change, and with that change the `serv_list` is only used when connecting the first time.

Your error indicates fault with `slots` on line 310, and that isn't correct with the latest code. Please check.

**Comment by Danixu** [comment] 2020-04-21 20:02
Thanks!!.

I'll take a look, because surely I'm not using the latest version. I had problems with other modules in the past, and I stick the build into a release version, and looks like is older than that merge.

Best regards.

**Comment by toredash** [comment] 2020-04-22 08:18
@Danixu I've made a PR #59 to allow redis to attempt reconnecting multiple times if it is not able to

I hope that combined with you using the latest code will help you

**Comment by i2dcarrasco** [comment] 2020-04-22 09:45
Thank you so much.

For now I had no time to test it, but I will try asap and I'll callback with the result.

Best regards.

**Comment by i2dcarrasco** [comment] 2020-05-29 07:12
Hello Toredash,

Sorry for late. Finally I was able to test it and seems to work, but I've a question that maybe is already fixed: Is possible to made a wait time until try the same node again?.
Works fine, but is trying to connect always to same node before jump to another and then it slowdown the script a lot, and is very important on a webpage.

if it doesn't exist I'll take a look to try if I can do it in any way.

Thanks!

**Comment by toredash** [comment] 2020-05-31 14:18
@i2dcarrasco any news?

**Comment by i2dcarrasco** [comment] 2020-06-01 06:56
For now there are no updates, just the above, works but trying to connect always to first node before jump to another.

I'm thinking about to create a "bantime" in the servers, and if one is non answering in time then set a time. During this time the server will not be asked for data. Anyway, for now is just an idea.

Best regards.

**Comment by toredash** [comment] 2020-06-30 08:12
@steve0511 please close this issue as OP hasn't provided more information

**Comment by orgerz** [comment] 2020-09-11 07:52
This still works wrong
When a node is down
a new connect is created by nginx worker
it failed in fetch_slots
well the cluster is working well
because it trying all the nodes in try_hosts_slots
one failed node will cause the fetch_slots error

**Comment by toredash** [comment] 2020-09-12 07:34
> This still works wrong
> When a node is down
> a new connect is created by nginx worker
> it failed in fetch_slots
> well the cluster is working well
> because it trying all the nodes in try_hosts_slots
> one failed node will cause the fetch_slots error

You need to provide more information. Are you sure your using the latest version of the code?

**Comment by orgerz** [comment] 2020-09-14 03:46
I've got the latest version, the problem is in try_hosts_slots
In case the cluster is OK, but the first node is down
even it goes through all the working nodes
the #errors is not nil, and try_hosts_slots will return error

**Comment by toredash** [comment] 2020-09-14 05:55
@orgerz Can you try this patch: https://github.com/toredash/resty-redis-cluster/commit/3dc421f5bc297e39b58dc09a0e8940fc2ad58ba6

I believe that would fix it. Please report back if it does

**Comment by orgerz** [comment] 2020-09-14 06:46
Thanks alot, it works fine

**Comment by toredash** [comment] 2020-09-15 11:59
thanks for reporting back, PR created

**Closed** 2020-09-15 14:41 UTC
